env:
  TERM: xterm-256color

import:
  - "~/.config/alacritty/dracula.yml"

selection:
  save_to_clipboard: true

window:
  option_as_alt: OnlyLeft
  dynamic_padding: true
  padding:
    x: 4
    y: 1

font:
  normal:
    family: FiraCode Nerd Font

  bold:
    family: FiraCode Nerd Font
    style: Bold

  italic:
    family: FiraCode Nerd Font
    style: Italic

  bold_italic:
    family: FiraCode Nerd Font
    style: Bold Italic

  size: 14

