env:
  TERM: xterm-256color

import:
  - "~/.config/alacritty/dracula.yml"

font:
  normal:
    family: FiraCode Nerd Font

  bold:
    family: FiraCode Nerd Font
    style: Bold

  italic:
    family: FiraCode Nerd Font
    style: Italic

  bold_italic:
    family: FiraCode Nerd Font
    style: Bold Italic

  size: 14

